import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Haiger Engineer",
  description: "Generated by Haiger Engineer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>{children}</body>
    </html>
  );
}
