import type { Metadata } from "next";
import "./globals.css";
// import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Haiger Engineer",
  description: "Generated by Haiger Engineer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        {/* <Navbar /> */}
        <Footer />
        {children}
      </body>
    </html>
  );
}
